### ISSUE TITLE
temperature alert not synced  - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#215] opened 2022-09-13 12:10 UTC
IOS  and Android show BB12 temperature alert max at 73. Email alert sent at 73.
Webui shows 75.
![TempAlertNotSynced](https://user-images.githubusercontent.com/2365961/189897246-eead4a44-dd4f-4edf-b9c3-8d0ef468822c.png)

**Comment by laurijamsa** [comment] 2022-10-07 07:15
I'd assume this is a some browser caching issue. Closing. Feel free to reopen if you can reproduce the issue.

**Closed by laurijamsa** 2022-10-07 07:15 UTC

**Comment by DG12** [comment] 2022-10-07 16:00
I don't think this was a browser cache issue, but I'll try to duplicate it and if I can I'll reopen this.

**Comment by io53** [comment] 2022-10-07 16:33
I think managed to reproduce this, but only once.
I set my temperature unit to F, then set an alert on iOS to 73F. Looking att the data from the cloud, the temperature limit is 23.8888888888913C.
Both iOS and Android shows that as 73F while Web shows 75F. (75F is the correct value for said degrees in C.)

But now when I try again I can no longer reproduce it. I do wonder tho if I was just fooled because iOS does not post the data immediately to the cloud.

@DG12 could you set the temperature unit to C and see what value the alert is set to?
