### ISSUE TITLE
multiSensor Window with settings F, title is F , graph is C

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#82] opened 2021-12-07 13:53 UTC
WIth the settings set to F
The screen showing multiple sensors
The title shows 38,17F but the graph is in C
<img width="511" alt="mulitsensorScreenFgrapsIsWrong" src="https://user-images.githubusercontent.com/2365961/145041298-79e18e98-f3dc-4e36-b742-3d8130384c49.png">

**Comment by laurijamsa** [comment] 2021-12-08 15:43
This seems to be a duplicate of the #76. Closing.

**Closed by laurijamsa** 2021-12-08 15:43 UTC

**Comment by DG12** [comment] 2021-12-08 15:57
Actually somewhat different. 
Issue#76 shows incorrect current reading ( 7,65F) as well incorrect graph (scale 6-9).

The current reading is now correct (38,17) but the graph is still wrong.
I suggest reopening this issue and closing issue #76 as this is more recent.

**Comment by laurijamsa** [comment] 2021-12-08 16:20
The both issues have been fixed on devstation.ruuvi.com and will be deployed soon to production.

**Comment by DG12** [comment] 2021-12-08 19:37
Yeah :clap: V0.2.3 ?

**Comment by laurijamsa** [comment] 2021-12-08 21:05
The devstation version seems to be currently 0.2.2, not 0.2.3, and so is
the production. I assume that the version number is updated only when
pushing changes to the production.

**Comment by DG12** [comment] 2021-12-08 21:13
Maybe it's just me, 
but at the present time devastation is not the same as webui wo I would expect them to be different versions. 
Just saying

**Comment by io53** [comment] 2021-12-08 21:16
That is true, it would probably make sense to bump the version in dev after updating production instead. Then dev would show newer version that production until it's updated.
