### ISSUE TITLE
offline emails sent too late, resolved sent too soon - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#404] opened 2024-04-12 20:51 UTC
Based on the attached screen shots, it appears the last packet from the sensor was received at 20:56. Given a 15 minute permitted outage before Alert I expect the alert email to be sent somewhere around 21:15. It was sent at 22:27.

The email resolved notification that the sensor was back online was sent at 22:45 however the first packet after the outage was at not until 22:56.

![image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/2365961/182d42eb-c57f-4653-a081-261b2676728f)

![image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/2365961/5368eb07-1d6f-4afd-b03e-a6b3f4099b21)

If this is not the correct repository for this issue please have it moved. Thank you.

**Comment by DG12** [comment] 2024-04-14 19:16
last evening at 4/13/24, 20:40:
`ruuvi 22AB has reached 57 minutes (offline) that is over the threshold of 15 minutes.
at 20:49:
ruuvi 22AB has reached 6 minutes (offline) that is inside the thresholds of 0 to 15 minutes.`

**Comment by laurijamsa** [comment] 2024-04-15 09:53
I assigned this to @ojousima hoping he can explain why this happened and then we can close this :)

**Comment by ojousima** [comment] 2024-04-15 12:28
I think I found the datapoints related to the outage, last one was at `1712796992, GMT: Thursday, 11th April 2024, 00.56` and first one after that `1712804235 GMT: Thursday, 11th April 2024, 02.57`. If your timezone is GMT-4 (Eastern USA) that would match. 

The delay for first offline warning email is a mystery, I don't see any errors on the logs. It could be that the email has been held back by some spam checker, some anti-spam system can hold emails for a short while before delivery. 

The resolved email sent before data is seen could be caused by our data pruning, the offline alert checking runs minute-by-minute and triggers as soon as there is fresh data. However the minute-by-minute data is pruned in 24 hours, which could leave only the long-term data viewable afterwards. 

Was there two outages before the second delayed email? The alerts are throttled to at max once per hour, so it could be that alert was waiting for a chance to retrigger. After triggering, alert has to wait at least 5 minutes before it can be resolved.

**Comment by markoaamunkajo** [comment] 2024-08-15 05:08
Closing this issue, we haven't seen such occurances lately

**Closed by markoaamunkajo** 2024-08-15 05:08 UTC
