### ISSUE TITLE
Sign in: activation code re-entering is not possible

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#167] opened 2022-04-30 03:00 UTC
Enter code incorrect reports 
"code used or expired"
no chance to reenter.  :-(

expired reports:

Unauthorized request.

??

**Comment by laurijamsa** [comment] 2022-05-05 03:47
I we would need some backend modification in order to show more detailed error messages (error type). IIRC we have a separate issue about it. But of course we could allow user to fix the code if it's actually just typed wrong and not expired or used, I think. Let's see what we can do. Not closing this one yet.

**Comment by DG12** [comment] 2022-05-07 12:16
@Lauri: The messages are backwards.
**expired** reports:unauthorized request(poor wording)
Wrong reports : used or **expired**

**Comment by lauri** [comment] 2022-05-07 14:48
Guys, stop mentioning me, I don't want to get involved 😄
(Although I do have a Ruuvi tag!)

**Comment by laurijamsa** [comment] 2022-10-20 07:56
I tried to reproduce this and it's true that on the web sign in page (current station.ruuvi.com and new ruuvi.com/station) we don't allow to re-enter the code if user typed it wrong. At least on Android user can re-enter it without requesting a new code. Let's enhance the ruuvi.com/station iframe login. No need to make the current station.ruuvi.com login page better because it's planned to be removed soonish.

**Closed** 2022-11-21 01:54 UTC
Labels: ready to deploy
